import type { Metadata } from "next";
import { Inter, Poppins } from 'next/font/google';
import "./globals.css";
import Navbar from "../components/NavBar";
import Footer from "../components/Footer";
import { getCmsContent } from "@/lib/content";
import AdminAwareChrome from "@/components/AdminAwareChrome";


// Configure Inter for Body
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter', 
});

// Configure Poppins for Headings
const poppins = Poppins({
  weight: ['500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins', 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cms = await getCmsContent();
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} antialiased`}
      >
        <AdminAwareChrome
          navbar={
            <Navbar
              logoSrc={cms.navbar.logoSrc}
              logoHref={cms.navbar.logoHref}
              links={cms.navbar.links}
              ctaLabel={cms.navbar.ctaLabel}
            />
          }
          footer={<Footer />}
        >
          {children}
        </AdminAwareChrome>
      </body>
    </html>
  );
}
